### ISSUE TITLE
Possible merger with ddnsc

### ISSUE THREAD

**Issue by ghost** [matt1/gandi-ddns#12]
[ddnsc](https://github.com/shyaminayesh/ddnsc) is a similar project, however it supports multiple dns providers. I think it would make sense to merge this project with ddnsc so there can be one package that supports many providers, especially since they are both already written in python.

**Comment by matt1** [comment]
Feel free to fork this repo and do the merger ddnsc.  I no longer have time or interest to do it myself.  Thanks.
